### ISSUE TITLE
TypeError after some time

### ISSUE THREAD

**Issue by ghost** [Kosat/telegram-messages-dump#2]
```
 $ python3 -m telegram_messages_dump -c @... -p ... -l 0                                                                                    
```
```
Initializing session...
Connecting to Telegram servers...
Chat name @... resolved into channel id=...
Dumping all messages into "telegram_....log" file ...
/usr/lib/python3.6/site-packages/telethon/telegram_client.py:1092: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Processing messages with ids 604580-604481 ...
Processing messages with ids 604480-604376 ...
Processing messages with ids 604375-604275 ...
Processing messages with ids 604274-604166 ...
Processing messages with ids 604165-604057 ...
Processing messages with ids 604055-603948 ...
Processing messages with ids 603947-603844 ...
Processing messages with ids 603843-603741 ...
Processing messages with ids 603740-603638 ...
Processing messages with ids 603637-603528 ...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fox/Code/python/telegram-messages-dump/telegram_messages_dump/__main__.py", line 6, in <module>
    run.main()
  File "/home/fox/Code/python/telegram-messages-dump/telegram_messages_dump/run.py", line 28, in main
    TelegramDumper(os.path.basename(__file__), settings).run()
  File "/home/fox/Code/python/telegram-messages-dump/telegram_messages_dump/telegram_dumper.py", line 82, in run
    count = self.dump_messages_in_file(chat)
  File "/home/fox/Code/python/telegram-messages-dump/telegram_messages_dump/telegram_dumper.py", line 215, in dump_messages_in_file
    with tempfile.TemporaryFile(mode='w+', encoding='utf-8', delete=False) as tf:
TypeError: TemporaryFile() got an unexpected keyword argument 'delete'
```

According to https://docs.python.org/3.6/library/tempfile.html there is no "delete" argument in  `tempfile.TemporaryFile` func but it present in `tempfile.NamedTemporaryFile`.

**Comment by Kosat** [comment]
Thank you.
Added this fix as part of commit 15c1579
